// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9U5EcQGD4TvE_JeuUCxitRuzror9rkvY',
    appId: '1:176908400957:web:890fa550d918dc8cd56d54',
    messagingSenderId: '176908400957',
    projectId: 'srmacademia-35d88',
    authDomain: 'srmacademia-35d88.firebaseapp.com',
    storageBucket: 'srmacademia-35d88.appspot.com',
    measurementId: 'G-FSZK6TL30D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vQGWEWumDwmaATVf6cU1kDt4Q986mlM',
    appId: '1:176908400957:android:87a7406f186405b2d56d54',
    messagingSenderId: '176908400957',
    projectId: 'srmacademia-35d88',
    storageBucket: 'srmacademia-35d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCuDUQN7MDdpxx8lDY6CsHg98qomRc3I',
    appId: '1:176908400957:ios:11771323947ee50ad56d54',
    messagingSenderId: '176908400957',
    projectId: 'srmacademia-35d88',
    storageBucket: 'srmacademia-35d88.appspot.com',
    iosClientId: '176908400957-n8jnhqms0uki1sc4vdpu0ofcp6dhvsgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmacadmia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCuDUQN7MDdpxx8lDY6CsHg98qomRc3I',
    appId: '1:176908400957:ios:11771323947ee50ad56d54',
    messagingSenderId: '176908400957',
    projectId: 'srmacademia-35d88',
    storageBucket: 'srmacademia-35d88.appspot.com',
    iosClientId: '176908400957-n8jnhqms0uki1sc4vdpu0ofcp6dhvsgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmacadmia',
  );
}
